development:
  adapter: postgresql
  database: mojito_dev
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  database: mojito_test
  host: localhost
  min_messages: WARNING

production:
  adapter: postgresql
  database: mojito_prod
  host: localhost
