development:
  adapter: postgresql
  database: tedxbalnearioipora_dev
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  database: tedxbalnearioipora_test
  host: localhost
  min_messages: WARNING

production:
  adapter: postgresql
  database: tedxbalnearioipora_prod
  host: localhost
